# Pre-build: gzip src/web/pages/*.html into a generated header of PROGMEM byte arrays.
# The ESP8266 sends pages synchronously over a slow link, so a 23KB dashboard stalls loop()
# and can arrive truncated; compressed it is about a quarter of the size.
Import("env")
import gzip, os

pages_dir = os.path.join(env.subst("$PROJECT_DIR"), "src", "web", "pages")
out_dir = os.path.join(env.subst("$BUILD_DIR"), "generated")
os.makedirs(out_dir, exist_ok=True)

lines = ["// Generated by scripts/embed_html.py - do not edit.", "#pragma once", "#include <pgmspace.h>", "#include <stddef.h>", ""]
for fname in sorted(os.listdir(pages_dir)):
    if not fname.endswith(".html"):
        continue
    ident = "k" + "".join(part.capitalize() for part in fname[:-5].split("_")) + "Gz"
    with open(os.path.join(pages_dir, fname), "rb") as f:
        data = gzip.compress(f.read(), compresslevel=9, mtime=0)  # mtime=0: reproducible output
    body = ",".join(str(b) for b in data)
    lines.append("static const unsigned char %s[] PROGMEM = {%s};" % (ident, body))
    lines.append("static const size_t %sLen = %d;" % (ident, len(data)))
    lines.append("")

path = os.path.join(out_dir, "web_pages.h")
content = "\n".join(lines)
if not os.path.exists(path) or open(path).read() != content:  # don't touch it if unchanged (avoids rebuilds)
    with open(path, "w") as f:
        f.write(content)
env.Append(CPPPATH=[out_dir])
