#include "WebHandler.h"
#include <ArduinoJson.h>
#include "../charging/output_component.h"
#include "../charging/EngineMode.h"
#include "../charging/StatusLed.h"
#include "../charging/VoltageCalibration.h"
#include "../charging/RealTimePid.h"
#include "../connectivity/MqttPublisher.h"
#include "../gps/GpsReader.h"
#include "../gps/GpsJumpFilter.h"
#include "../gps/SpeedAverager.h"
#include <time.h>
#include "web_pages.h" // generated by scripts/embed_html.py from src/web/pages/*.html (gzip)

namespace {
// Before NTP sync completes, time(nullptr) returns a small/near-zero value.
// Anything before ~2023 is treated as "not synced yet".
constexpr time_t kMinPlausibleEpoch = 1700000000;

uint32_t current_epoch_or_zero() {
  time_t now = time(nullptr);
  return now >= kMinPlausibleEpoch ? static_cast<uint32_t>(now) : 0;
}
}

ESP8266WebServer server(80);
extern OutputComponent alternator;
extern DataPoint history[];
extern byte historyIndex;
extern bool engine_running;
extern bool engine_probing;
extern bool overvoltage_alert;
extern bool wifiConnectedSta;
extern int staAttempts;
extern int staLastFailStatus;
extern unsigned long maxLoopDurationUs;
extern unsigned long peakLoopUs, peakWifiUs, peakWebUs, peakMqttUs, peakFlashUs;
extern MqttPublisher mqttPublisher;
extern const char* mqtt_host;
extern GpsReader gpsReader;
extern EngineModeSettings engineModeSettings;
extern SpeedAverager gpsSpeedAvg;
extern VoltageCalibration voltageCalibration;
extern float unscaledVoltage;
extern RealTimePid chargePID;
extern LedFault activeFault;
extern LedFault lastFault;
extern unsigned long lastFaultMillis;
extern GpsJumpFilter gpsJumpFilter;
extern bool gpsHasAcceptedFix;
extern const char* ap_password;
bool web_initialized = false;

namespace {
// Endpoints that change state (autotune, engine mode, maintenance, restart, MQTT retry) ask
// for HTTP basic auth: user "admin", password = the AP password from secrets.h. Read-only
// pages (dashboard, /data, /history, logbook view) stay open. An empty AP password disables it.
bool authorized() {
  if (ap_password[0] == '\0' || server.authenticate("admin", ap_password)) return true;
  server.requestAuthentication();
  return false;
}
typedef void (*Handler)();
ESP8266WebServer::THandlerFunction guarded(Handler h) {
  return [h]() { if (authorized()) h(); };
}
}

void setupWebServer() {
  if (!web_initialized) {
    server.on("/", handleRoot);
    server.on("/data", handleData);
    server.on("/history", handleHistory);
    server.on("/autotune/start", guarded(handleAutotuneStart));
    server.on("/maintenance/reset", guarded(handleMaintenanceReset));
    server.on("/maintenance/interval", guarded(handleMaintenanceInterval));
    server.on("/maintenance", handleMaintenancePage);
    server.on("/maintenance/log", handleMaintenanceLogList);
    server.on("/maintenance/log/add", guarded(handleMaintenanceLogAdd));
    server.on("/restart", guarded(handleRestart)); // remote recovery when there's no physical/USB access
    server.on("/mqtt/test", guarded(handleMqttTest));
    server.on("/engine/sources", guarded(handleEngineSources));
    server.on("/voltage/calibrate", guarded(handleVoltageCalibration));
    server.onNotFound(handleNotFound); // captive portal: unknown host/path -> redirect to the dashboard
    server.collectHeaders("If-None-Match");
    server.begin();
    Serial.println("Web server started");
    web_initialized = true;
  }
}

// Captive-portal probes and stray requests (favicon, ...) get a tiny reply instead of the
// whole ~22KB dashboard: a synchronous send of that size stalls loop() on a weak link.
void handleNotFound() {
  if (server.uri() == "/favicon.ico") { server.send(204); return; }
  server.sendHeader("Location", String("http://") + server.client().localIP().toString() + "/", true);
  server.send(302, "text/plain", "");
}

// The dashboard (src/web/pages/dashboard.html) is ~23KB raw, ~6KB gzipped, and the ESP8266 serves one connection at a time, so a cold load
// competes with the browser's other requests and can arrive truncated on a slow link. The
// ETag changes with every firmware build: the browser revalidates (tiny 304) instead of
// re-downloading the page on every visit.
static const char kDashboardEtag[] = "\"" __DATE__ " " __TIME__ "\"";

void handleRoot() {
  if (server.hasHeader("If-None-Match") && server.header("If-None-Match") == kDashboardEtag) {
    server.send(304);
    return;
  }
  server.sendHeader("ETag", kDashboardEtag);
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Content-Encoding", "gzip");
  server.send_P(200, "text/html", reinterpret_cast<PGM_P>(kDashboardGz), kDashboardGzLen);
}

void handleData() {
  DynamicJsonDocument doc(1536); // ~35 fields at 16B each + copied Strings; 512 silently dropped the tail
  doc["voltage"] = history[(historyIndex + HISTORY_SIZE - 1) % HISTORY_SIZE].voltage;
  doc["outputMode"] = alternator.isPWMEnabled() ? "pwm" : "relay";
  doc["pwmPercentage"] = alternator.getPWMPercent();
  doc["engineRunning"] = engine_running;
  doc["engineProbing"] = engine_probing;
  doc["overvoltageAlert"] = overvoltage_alert;
  doc["engineSources"] = engineModeSettings.sources();
  doc["voltageScale"] = voltageCalibration.scale();
  doc["pidKp"] = chargePID.kp();
  doc["pidKi"] = chargePID.ki();
  doc["pidKd"] = chargePID.kd();
  doc["fault"] = static_cast<int>(activeFault);  // LED blink code, 0 = none
  doc["lastFault"] = static_cast<int>(lastFault);
  doc["lastFaultAgoS"] = (millis() - lastFaultMillis) / 1000;
  doc["gpsConnected"] = gpsReader.isConnected();
  doc["gpsHasFix"] = gpsHasAcceptedFix;
  if (gpsHasAcceptedFix) {
    // filtered position (see GpsJumpFilter) - rejects fixes implying an impossible
    // speed, so a momentary GPS glitch doesn't show the tractor teleporting
    doc["gpsLat"] = gpsJumpFilter.lastLat();
    doc["gpsLon"] = gpsJumpFilter.lastLon();
    doc["gpsSpeedKmh"] = gpsReader.speedKmh();
    doc["gpsSpeedAvgKmh"] = gpsSpeedAvg.average(millis());
  }

  doc["wifiMode"] = wifiConnectedSta ? "sta" : "ap_fallback";
  doc["staAttempts"] = staAttempts;
  doc["staLastFail"] = staLastFailStatus;

  doc["autotuneActive"] = autotuneActive;
  doc["runHours"] = usageCounters.totalRunSeconds() / 3600.0;
  doc["secondsSinceService_h"] = usageCounters.secondsSinceService() / 3600.0;
  doc["serviceIntervalHours"] = usageCounters.serviceIntervalHours();
  doc["maintenanceDue"] = usageCounters.isMaintenanceDue();
  doc["bootCount"] = usageCounters.bootCount();
  doc["freeHeap"] = ESP.getFreeHeap();
  doc["resetReason"] = ESP.getResetReason();
  doc["resetInfo"] = ESP.getResetInfo();
  doc["wifiModeRaw"] = (int)WiFi.getMode();
  doc["softApIp"] = WiFi.softAPIP().toString();
  doc["softApStations"] = WiFi.softAPgetStationNum();
  doc["maxFreeBlock"] = ESP.getMaxFreeBlockSize();
  doc["heapFrag"] = ESP.getHeapFragmentation();
  doc["loopTimeUs"] = peakLoopUs > maxLoopDurationUs ? peakLoopUs : maxLoopDurationUs; // 60s peak
  doc["loopWifiUs"] = peakWifiUs;
  doc["loopWebUs"] = peakWebUs;
  doc["loopMqttUs"] = peakMqttUs;
  doc["loopFlashUs"] = peakFlashUs;

  doc["mqttConnected"] = mqttPublisher.isConnected();
  doc["mqttHasLastPublish"] = mqttPublisher.hasLastPublished();
  if (mqttPublisher.hasLastPublished()) {
    const MqttReading& last = mqttPublisher.lastPublished();
    doc["mqttLastVoltage"] = last.voltage;
    doc["mqttLastPwmPercent"] = alternator.getMaxPWM() ? (last.pwmValue * 100 / alternator.getMaxPWM()) : 0;
    doc["mqttLastSentAgoS"] = (millis() - mqttPublisher.lastPublishMillis()) / 1000;
  }

  String json;
  serializeJson(doc, json);
  server.send(200, "application/json", json);
}

void handleHistory() {
  // Streamed in chunks: a JsonDocument holding all HISTORY_SIZE points needs ~10KB of
  // heap (and a 4KB one silently kept only the oldest ~50), so build it piecewise instead.
  server.setContentLength(CONTENT_LENGTH_UNKNOWN);
  server.send(200, "application/json", "");

  char chunk[512];
  size_t len = 0;
  chunk[len++] = '[';
  bool first = true;
  for(int i = 0; i < HISTORY_SIZE; i++) {
    int idx = (historyIndex + i) % HISTORY_SIZE;
    if(history[idx].timestamp == 0) continue;

    if(len > sizeof(chunk) - 80) {
      chunk[len] = '\0';
      server.sendContent(chunk);
      len = 0;
    }
    len += snprintf(chunk + len, sizeof(chunk) - len, "%s{\"timestamp\":%lu,\"voltage\":%.2f,\"pwm\":%u}",
                    first ? "" : ",", history[idx].timestamp, history[idx].voltage, history[idx].pwmValue);
    first = false;
  }
  chunk[len++] = ']';
  chunk[len] = '\0';
  server.sendContent(chunk);
  server.sendContent("");
}

void handleAutotuneStart() {
  start_pid_autotune();
  server.send(200, "application/json", "{\"ok\":true}");
}

void handleMaintenanceReset() {
  usageCounters.resetMaintenanceCounter();
  server.send(200, "application/json", "{\"ok\":true}");
}

// /voltage/calibrate?volts=13.8  -> scale = multimeter reading / what the device currently reads
// /voltage/calibrate?reset=1     -> back to the factory divider calibration
void handleVoltageCalibration() {
  if (server.hasArg("reset")) {
    voltageCalibration.reset();
  } else if (server.hasArg("volts")) {
    if (!voltageCalibration.calibrate(server.arg("volts").toFloat(), unscaledVoltage)) {
      server.send(400, "application/json",
                  "{\"ok\":false,\"error\":\"Reading rejected: must be 6-20V and within 20% of what the device measures\"}");
      return;
    }
  }
  server.send(200, "application/json", String("{\"ok\":true,\"scale\":") + String(voltageCalibration.scale(), 4) + "}");
}

void handleEngineSources() {
  if (server.hasArg("mask")) {
    long mask = server.arg("mask").toInt();
    engineModeSettings.setSources(static_cast<uint8_t>(mask < 0 || mask > 255 ? 0 : mask)); // invalid -> default
  }
  server.send(200, "application/json", String("{\"sources\":") + engineModeSettings.sources() + "}");
}

void handleMaintenanceInterval() {
  if (server.hasArg("hours")) {
    long hours = server.arg("hours").toInt();
    if (hours > 0) usageCounters.setServiceIntervalHours(static_cast<uint32_t>(hours));
  }
  server.send(200, "application/json", "{\"ok\":true}");
}

void handleMaintenancePage() {
  server.sendHeader("Content-Encoding", "gzip");
  server.send_P(200, "text/html", reinterpret_cast<PGM_P>(kMaintenanceGz), kMaintenanceGzLen);
}

void handleMaintenanceLogList() {
  MaintenanceLogEntry entries[64];
  size_t count = maintenanceLog.getEntries(entries, 64);

  DynamicJsonDocument doc(4096);
  JsonArray array = doc.to<JsonArray>();
  for (size_t i = 0; i < count; i++) {
    JsonObject e = array.createNestedObject();
    e["epoch"] = entries[i].epochSeconds;
    e["hours"] = entries[i].runHours;
    e["note"] = entries[i].note;
  }

  String json;
  serializeJson(doc, json);
  server.send(200, "application/json", json);
}

void handleMaintenanceLogAdd() {
  String note = server.hasArg("note") ? server.arg("note") : "";
  maintenanceLog.addEntry(current_epoch_or_zero(), usageCounters.totalRunSeconds() / 3600, note.c_str());
  server.send(200, "application/json", "{\"ok\":true}");
}

void handleMqttTest() {
  mqttPublisher.forceReconnectNow();
  server.send(200, "application/json", "{\"ok\":true}");
}

void handleRestart() {
  server.send(200, "application/json", "{\"ok\":true}");
  server.client().flush();
  delay(100); // let the response actually go out before rebooting
  ESP.restart();
}
