#include "WebHandler.h"
#include <ArduinoJson.h>
#include "../charging/output_component.h"
#include "../charging/EngineMode.h"
#include "../charging/StatusLed.h"
#include "../charging/VoltageCalibration.h"
#include "../charging/RealTimePid.h"
#include "../charging/PidSettings.h"
#include "../connectivity/MqttPublisher.h"
#include "../gps/GpsReader.h"
#include "../gps/GpsJumpFilter.h"
#include "../gps/SpeedAverager.h"
#include "../gps/TrackRecorder.h"
#include <time.h>
#include "web_pages.h" // generated by scripts/embed_html.py from src/web/pages/*.html (gzip)

namespace {
// Before NTP sync completes, time(nullptr) returns a small/near-zero value.
// Anything before ~2023 is treated as "not synced yet".
constexpr time_t kMinPlausibleEpoch = 1700000000;

uint32_t current_epoch_or_zero() {
  time_t now = time(nullptr);
  return now >= kMinPlausibleEpoch ? static_cast<uint32_t>(now) : 0;
}
}

ESP8266WebServer server(80);
extern OutputComponent alternator;
extern DataPoint history[];
extern byte historyIndex;
extern bool engine_running;
extern bool engine_probing;
extern bool overvoltage_alert;
extern bool wifiConnectedSta;
extern int staAttempts;
extern int staLastFailStatus;
extern unsigned long maxLoopDurationUs;
extern unsigned long peakLoopUs, peakWifiUs, peakWebUs, peakMqttUs, peakFlashUs;
extern MqttPublisher mqttPublisher;
extern const char* mqtt_host;
extern GpsReader gpsReader;
extern EngineModeSettings engineModeSettings;
extern SpeedAverager gpsSpeedAvg;
extern TrackRecorder trackRecorder;
extern VoltageCalibration voltageCalibration;
extern float unscaledVoltage;
extern RealTimePid chargePID;
extern PidSettings pidSettings;
extern LedFault activeFault;
extern LedFault lastFault;
extern unsigned long lastFaultMillis;
extern GpsJumpFilter gpsJumpFilter;
extern bool gpsHasAcceptedFix;
extern const char* ap_password;
bool web_initialized = false;

namespace {
// Endpoints that change state (autotune, engine mode, maintenance, restart, MQTT retry) ask
// for HTTP basic auth: user "admin", password = the AP password from secrets.h. Read-only
// pages (dashboard, /data, /history, logbook view) stay open. An empty AP password disables it.
bool authorized() {
  if (ap_password[0] == '\0' || server.authenticate("admin", ap_password)) return true;
  server.requestAuthentication();
  return false;
}
typedef void (*Handler)();
ESP8266WebServer::THandlerFunction guarded(Handler h) {
  return [h]() { if (authorized()) h(); };
}
}

void setupWebServer() {
  if (!web_initialized) {
    server.on("/", handleRoot);
    server.on("/data", handleData);
    server.on("/history", handleHistory);
    server.on("/autotune/start", guarded(handleAutotuneStart));
    server.on("/maintenance/reset", guarded(handleMaintenanceReset));
    server.on("/maintenance/interval", guarded(handleMaintenanceInterval));
    server.on("/maintenance", handleMaintenancePage);
    server.on("/maintenance/log", handleMaintenanceLogList);
    server.on("/maintenance/log/add", guarded(handleMaintenanceLogAdd));
    server.on("/restart", guarded(handleRestart)); // remote recovery when there's no physical/USB access
    server.on("/mqtt/test", guarded(handleMqttTest));
    server.on("/engine/sources", guarded(handleEngineSources));
    server.on("/voltage/calibrate", guarded(handleVoltageCalibration));
    server.on("/alternator/pause", guarded(handleAlternatorPause));
    server.on("/track", handleTrack);
    server.on("/track.gpx", handleTrackGpx);
    server.on("/track/clear", guarded(handleTrackClear));
    server.on("/pid/reset", guarded(handlePidReset));
    server.onNotFound(handleNotFound); // captive portal: unknown host/path -> redirect to the dashboard
    server.collectHeaders("If-None-Match");
    server.begin();
    Serial.println(F("Web server started"));
    web_initialized = true;
  }
}

// Captive-portal probes and stray requests (favicon, ...) get a tiny reply instead of the
// whole ~22KB dashboard: a synchronous send of that size stalls loop() on a weak link.
void handleNotFound() {
  if (server.uri() == "/favicon.ico") { server.send(204); return; }
  server.sendHeader("Location", String("http://") + server.client().localIP().toString() + "/", true);
  server.send(302, "text/plain", "");
}

// The dashboard (src/web/pages/dashboard.html) is ~23KB raw, ~6KB gzipped, and the ESP8266 serves one connection at a time, so a cold load
// competes with the browser's other requests and can arrive truncated on a slow link. The
// ETag changes with every firmware build: the browser revalidates (tiny 304) instead of
// re-downloading the page on every visit.
static const char kDashboardEtag[] = "\"" __DATE__ " " __TIME__ "\"";

void handleRoot() {
  if (server.hasHeader("If-None-Match") && server.header("If-None-Match") == kDashboardEtag) {
    server.send(304);
    return;
  }
  server.sendHeader("ETag", kDashboardEtag);
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Content-Encoding", "gzip");
  server.send_P(200, "text/html", reinterpret_cast<PGM_P>(kDashboardGz), kDashboardGzLen);
}

void handleData() {
  DynamicJsonDocument doc(2560); // keys copied from flash (F()) count against the pool // ~35 fields at 16B each + copied Strings; 512 silently dropped the tail
  doc[F("voltage")] = history[(historyIndex + HISTORY_SIZE - 1) % HISTORY_SIZE].voltage;
  doc[F("outputMode")] = alternator.isPWMEnabled() ? "pwm" : "relay";
  doc[F("pwmPercentage")] = alternator.getPWMPercent();
  doc[F("engineRunning")] = engine_running;
  doc[F("engineProbing")] = engine_probing;
  doc[F("overvoltageAlert")] = overvoltage_alert;
  doc[F("engineSources")] = engineModeSettings.sources();
  doc[F("voltageScale")] = voltageCalibration.scale();
  doc[F("pidKp")] = chargePID.kp();
  doc[F("pidKi")] = chargePID.ki();
  doc[F("pidKd")] = chargePID.kd();
  doc[F("pidCustom")] = pidSettings.hasCustom();
  doc[F("alternatorPausedS")] = (alternator_pause_remaining_ms() + 999) / 1000;
  doc[F("fault")] = static_cast<int>(activeFault);  // LED blink code, 0 = none
  doc[F("lastFault")] = static_cast<int>(lastFault);
  doc[F("lastFaultAgoS")] = (millis() - lastFaultMillis) / 1000;
  doc[F("gpsConnected")] = gpsReader.isConnected();
  doc[F("gpsHasFix")] = gpsHasAcceptedFix;
  doc[F("trackPoints")] = trackRecorder.size();
  doc[F("trackDistanceM")] = trackRecorder.distanceMeters();
  if (gpsHasAcceptedFix) {
    // filtered position (see GpsJumpFilter) - rejects fixes implying an impossible
    // speed, so a momentary GPS glitch doesn't show the tractor teleporting
    doc[F("gpsLat")] = gpsJumpFilter.lastLat();
    doc[F("gpsLon")] = gpsJumpFilter.lastLon();
    doc[F("gpsSpeedKmh")] = gpsReader.speedKmh();
    doc[F("gpsSpeedAvgKmh")] = gpsSpeedAvg.average(millis());
  }

  doc[F("wifiMode")] = wifiConnectedSta ? "sta" : "ap_fallback";
  doc[F("staAttempts")] = staAttempts;
  doc[F("staLastFail")] = staLastFailStatus;

  doc[F("autotuneActive")] = autotuneActive;
  doc[F("runHours")] = usageCounters.totalRunSeconds() / 3600.0;
  doc[F("secondsSinceService_h")] = usageCounters.secondsSinceService() / 3600.0;
  doc[F("serviceIntervalHours")] = usageCounters.serviceIntervalHours();
  doc[F("maintenanceDue")] = usageCounters.isMaintenanceDue();
  doc[F("bootCount")] = usageCounters.bootCount();
  doc[F("freeHeap")] = ESP.getFreeHeap();
  doc[F("cpuMHz")] = ESP.getCpuFreqMHz();
  doc[F("resetReason")] = ESP.getResetReason();
  doc[F("resetInfo")] = ESP.getResetInfo();
  doc[F("wifiModeRaw")] = (int)WiFi.getMode();
  doc[F("softApIp")] = WiFi.softAPIP().toString();
  doc[F("softApStations")] = WiFi.softAPgetStationNum();
  doc[F("maxFreeBlock")] = ESP.getMaxFreeBlockSize();
  doc[F("heapFrag")] = ESP.getHeapFragmentation();
  doc[F("loopTimeUs")] = peakLoopUs > maxLoopDurationUs ? peakLoopUs : maxLoopDurationUs; // 60s peak
  doc[F("loopWifiUs")] = peakWifiUs;
  doc[F("loopWebUs")] = peakWebUs;
  doc[F("loopMqttUs")] = peakMqttUs;
  doc[F("loopFlashUs")] = peakFlashUs;

  doc[F("mqttConnected")] = mqttPublisher.isConnected();
  doc[F("mqttHasLastPublish")] = mqttPublisher.hasLastPublished();
  if (mqttPublisher.hasLastPublished()) {
    const MqttReading& last = mqttPublisher.lastPublished();
    doc[F("mqttLastVoltage")] = last.voltage;
    doc[F("mqttLastPwmPercent")] = alternator.getMaxPWM() ? (last.pwmValue * 100 / alternator.getMaxPWM()) : 0;
    doc[F("mqttLastSentAgoS")] = (millis() - mqttPublisher.lastPublishMillis()) / 1000;
  }

  String json;
  serializeJson(doc, json);
  server.send(200, "application/json", json);
}

void handleHistory() {
  // Streamed in chunks: a JsonDocument holding all HISTORY_SIZE points needs ~10KB of
  // heap (and a 4KB one silently kept only the oldest ~50), so build it piecewise instead.
  server.setContentLength(CONTENT_LENGTH_UNKNOWN);
  server.send(200, "application/json", "");

  char chunk[512];
  size_t len = 0;
  chunk[len++] = '[';
  bool first = true;
  for(int i = 0; i < HISTORY_SIZE; i++) {
    int idx = (historyIndex + i) % HISTORY_SIZE;
    if(history[idx].timestamp == 0) continue;

    if(len > sizeof(chunk) - 80) {
      chunk[len] = '\0';
      server.sendContent(chunk);
      len = 0;
    }
    len += snprintf(chunk + len, sizeof(chunk) - len, "%s{\"timestamp\":%lu,\"voltage\":%.2f,\"pwm\":%u}",
                    first ? "" : ",", history[idx].timestamp, history[idx].voltage, history[idx].pwmValue);
    first = false;
  }
  chunk[len++] = ']';
  chunk[len] = '\0';
  server.sendContent(chunk);
  server.sendContent("");
}

void handleAutotuneStart() {
  start_pid_autotune();
  server.send_P(200, PSTR("application/json"), PSTR("{\"ok\":true}"));
}

void handleMaintenanceReset() {
  usageCounters.resetMaintenanceCounter();
  server.send_P(200, PSTR("application/json"), PSTR("{\"ok\":true}"));
}

// /voltage/calibrate?volts=13.8  -> scale = multimeter reading / what the device currently reads
// /voltage/calibrate?reset=1     -> back to the factory divider calibration
void handleVoltageCalibration() {
  if (server.hasArg("reset")) {
    voltageCalibration.reset();
  } else if (server.hasArg("volts")) {
    // "shown" = what the dashboard displayed when the multimeter was read (the voltage moves, so
    // the device's own reading at request time would be a different number). Falls back to now.
    float measured = server.arg("volts").toFloat();
    bool ok = server.hasArg("shown") ? voltageCalibration.calibrateFromShown(measured, server.arg("shown").toFloat())
                                     : voltageCalibration.calibrate(measured, unscaledVoltage);
    if (!ok) {
      server.send(400, "application/json",
                  "{\"ok\":false,\"error\":\"Reading rejected: must be 6-20V and within 20% of what the device measures\"}");
      return;
    }
  }
  server.send(200, "application/json", String("{\"ok\":true,\"scale\":") + String(voltageCalibration.scale(), 4) + "}");
}

// /alternator/pause?seconds=20 holds the field off (max 30s) so the voltage settles while it is
// compared with a multimeter; /alternator/pause?seconds=0 resumes right away.
void handleAlternatorPause() {
  long seconds = server.hasArg("seconds") ? server.arg("seconds").toInt() : 20;
  if (seconds <= 0) resume_alternator();
  else pause_alternator(static_cast<unsigned long>(seconds) * 1000UL);
  server.send(200, "application/json", String("{\"ok\":true,\"pausedS\":") + (alternator_pause_remaining_ms() + 999) / 1000 + "}");
}

// Back to the factory Kp/Ki/Kd, forgetting the saved (autotuned) ones.
void handlePidReset() {
  pidSettings.resetToFactory();
  PidGains g = pidSettings.gains();
  chargePID.setTunings(g.kp, g.ki, g.kd);
  server.send_P(200, PSTR("application/json"), PSTR("{\"ok\":true}"));
}

// /track: the track for the dashboard map, streamed as JSON. Thinned to ~600 points when it is
// longer (a bigger body stalls the single-threaded server on a slow link) - segment breaks are
// always kept (as null) so sessions are never joined by a line.
void handleTrack() {
  const size_t kMaxMapPoints = 600;
  size_t n = trackRecorder.size();
  size_t stride = n > kMaxMapPoints ? (n + kMaxMapPoints - 1) / kMaxMapPoints : 1;

  server.setContentLength(CONTENT_LENGTH_UNKNOWN);
  server.send(200, "application/json", "");
  char chunk[400];
  size_t len = snprintf(chunk, sizeof(chunk), "{\"count\":%u,\"distanceM\":%.0f,\"points\":[",
                        static_cast<unsigned>(n), trackRecorder.distanceMeters());
  bool first = true;
  TrackPoint batch[16];
  for(size_t at = 0; at < n;) {
    size_t got = trackRecorder.read(at, batch, 16);
    if(got == 0) break;
    for(size_t i = 0; i < got; i++) {
      size_t idx = at + i;
      if(!is_segment_break(batch[i]) && idx % stride != 0 && idx != n - 1) continue;
      if(len > sizeof(chunk) - 40) { server.sendContent(chunk); len = 0; }
      if(is_segment_break(batch[i])) len += snprintf(chunk + len, sizeof(chunk) - len, "%snull", first ? "" : ",");
      else len += snprintf(chunk + len, sizeof(chunk) - len, "%s[%ld,%ld]", first ? "" : ",",
                           static_cast<long>(batch[i].latE6), static_cast<long>(batch[i].lonE6));
      first = false;
    }
    at += got;
  }
  len += snprintf(chunk + len, sizeof(chunk) - len, "]}");
  server.sendContent(chunk);
  server.sendContent("");
}

// /track.gpx: everything recorded as a GPX file (opens in any GPS/maps app), one <trkseg> per
// session. Can be several seconds of sending, so the control loop is serviced between chunks.
void handleTrackGpx() {
  server.setContentLength(CONTENT_LENGTH_UNKNOWN);
  server.sendHeader("Content-Disposition", "attachment; filename=\"tractor-track.gpx\"");
  server.send(200, "application/gpx+xml", "");
  server.sendContent(kGpxHeader);

  char chunk[480];
  size_t len = 0;
  bool wroteAny = false;
  TrackPoint batch[8];
  size_t total = trackRecorder.size();
  for(size_t at = 0; at < total;) {
    size_t got = trackRecorder.read(at, batch, 8);
    if(got == 0) break;
    for(size_t i = 0; i < got; i++) {
      size_t n;
      if(is_segment_break(batch[i])) {
        if(!wroteAny) continue; // the first session opens the segment already written by the header
        n = snprintf(chunk + len, sizeof(chunk) - len, "%s", kGpxSegmentBreak);
        if(n >= sizeof(chunk) - len) n = 0;
      } else {
        n = gpx_format_point(chunk + len, sizeof(chunk) - len, batch[i]);
        wroteAny = true;
      }
      if(n == 0) { // chunk full: flush, then retry this item
        chunk[len] = '\0';
        server.sendContent(chunk);
        control_tick(); // keep regulating the alternator while the browser is being fed
        len = 0;
        n = is_segment_break(batch[i]) ? snprintf(chunk, sizeof(chunk), "%s", kGpxSegmentBreak)
                                       : gpx_format_point(chunk, sizeof(chunk), batch[i]);
      }
      len += n;
    }
    at += got;
  }
  chunk[len] = '\0';
  if(len) server.sendContent(chunk);
  server.sendContent(kGpxFooter);
  server.sendContent("");
}

void handleTrackClear() {
  trackRecorder.clear();
  server.send_P(200, PSTR("application/json"), PSTR("{\"ok\":true}"));
}

void handleEngineSources() {
  if (server.hasArg("mask")) {
    long mask = server.arg("mask").toInt();
    engineModeSettings.setSources(static_cast<uint8_t>(mask < 0 || mask > 255 ? 0 : mask)); // invalid -> default
  }
  server.send(200, "application/json", String("{\"sources\":") + engineModeSettings.sources() + "}");
}

void handleMaintenanceInterval() {
  if (server.hasArg("hours")) {
    long hours = server.arg("hours").toInt();
    if (hours > 0) usageCounters.setServiceIntervalHours(static_cast<uint32_t>(hours));
  }
  server.send_P(200, PSTR("application/json"), PSTR("{\"ok\":true}"));
}

void handleMaintenancePage() {
  server.sendHeader("Content-Encoding", "gzip");
  server.send_P(200, "text/html", reinterpret_cast<PGM_P>(kMaintenanceGz), kMaintenanceGzLen);
}

void handleMaintenanceLogList() {
  MaintenanceLogEntry entries[64];
  size_t count = maintenanceLog.getEntries(entries, 64);

  DynamicJsonDocument doc(4096);
  JsonArray array = doc.to<JsonArray>();
  for (size_t i = 0; i < count; i++) {
    JsonObject e = array.createNestedObject();
    e["epoch"] = entries[i].epochSeconds;
    e["hours"] = entries[i].runHours;
    e["note"] = entries[i].note;
  }

  String json;
  serializeJson(doc, json);
  server.send(200, "application/json", json);
}

void handleMaintenanceLogAdd() {
  String note = server.hasArg("note") ? server.arg("note") : "";
  maintenanceLog.addEntry(current_epoch_or_zero(), usageCounters.totalRunSeconds() / 3600, note.c_str());
  server.send_P(200, PSTR("application/json"), PSTR("{\"ok\":true}"));
}

void handleMqttTest() {
  mqttPublisher.forceReconnectNow();
  server.send_P(200, PSTR("application/json"), PSTR("{\"ok\":true}"));
}

void handleRestart() {
  server.send_P(200, PSTR("application/json"), PSTR("{\"ok\":true}"));
  server.client().flush();
  delay(100); // let the response actually go out before rebooting
  ESP.restart();
}
